theme: jekyll-theme-cayman
title: Курс «Продвинутое программирование на Python»
description: Здесь будет описание нашего курса
show_downloads: true
github:
  zip_url: https://ict.herzen.spb.ru/user/data/documents/cepo-conf-2022/Программа_Конф_22_25_Февраля_Краткая.pdf
